[features]
seeds = false
skip-lint = false
[programs.localnet]
staking_shii = "tUhgH4UM8cjTTRJo8TLAaPR5SikDAoMdfCms5ZsnSSK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/Dudeiebeech/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
